/**
 * Created by nnnyy on 2018-11-24.
 */
const VueBus = {
    CloseInventory: "CloseInentory",
    StartTimer: "StartTimer",
    SetAlertMsg: "SetAlertMsg",
    OpenGachaBox: "OpenGachaBox",
    OpenTopServerListMenu: "OpenTopServerListMenu",
    OpenSettings: "OpenSettings",
    OpenChatLog: "OpenChatLog",
    OpenVoteLog: "OpenVoteLog",
    OpenSearchLog: "OpenSearchLog",
    OpenUserInfo: "OpenUserInfo",
    OpenQuizTable: "OpenQuizTable",
    Mode: "Mode",
    SetChatFocus: "SetChatFocus",
    Search: "Search",
    SearchRet: "SearchRet",
    SearchRetRight: "SearchRetRight",
    MarkSearchContent: "MarkSearchContent",
    Resize: "Resize",
    ChatLRChange: "ChatLRChange",
    SOCK: {
        NotLogined: "NotLogined",
        LoginRequest: "LoginRequest",
        Disconnect: "disconnect",
        QuizData: "QuizData",
        QuizDataResult: "QuizDataResult",
        QuizAnswer: "QuizAnswer",
        AlertMsg: "AlertMsg",
        ComboInfo: "ComboInfo",
        Logout: "Logout",
        QuizAnswerCnt: "QuizAnswerCnt",
        CurrentComboRank: "CurrentComboRank",
        AnswerFirstSelectUser: "AnswerFirstSelectUser",
        QuizRecordRank: "QuizRecordRank",
        Vote:"Vote",
        VoteData: "VoteData",
        ServerInfo: "ServerInfo",
        FlushChat: "FlushChat",
        RequestChatLog: "RequestChatLog",
        RequestVoteLog: "RequestVoteLog",
        RequestSearchLog: "RequestSearchLog",
        Chat: "Chat",
        CenterData: "CenterData",
        Notice: "Notice",
        Hint: "global-hint",
        Search: "search",
        SendSearchQueryToCenter: "search-query",
        ChangeServer: "ChangeServer",
        RequestSearch: "RequestSearch",
        RequestBan: "RequestBan",
        RequestLike: "RequestLike",
        GetRankingData: "GetRankingData",
        GetLevelList: "GetLevelList",
        GetTimeTableList: "GetTimeTableList",
        UpdatePoint: "UpdatePoint",
        ChosungGame: "ChosungGame",
        OXGame: "OXGame",
        OXGameToUser: "OXGameToUser"
    }
};

module.exports = VueBus;